### ISSUE TITLE
Group comics with similar name like in original Chunky

### ISSUE THREAD

**Issue by jlnprssnr** [mike-ferenduros/ChunkyTNG-issues#37]
This would be very helpful! I noticed that with Image Comics sync, it will group comics into a folder like Descender, titled:
Descender, Vol. 2 TP
Descender, Vol. 3: Singularities TP
Descender, Vol. 4: Orbital Mechanics TP
Descender, Vol. 5: Rise Of The Robots TP

https://i.imgur.com/rmrXZJ2.jpg
https://i.imgur.com/cQnqtha.jpg

but with comics from Humble Bundle, it will not group comics, for example those titled:

All Hail Megatron, Vol. 1
All Hail Megatron, Vol. 2
All Hail Megatron, Vol. 3
All Hail Megatron, Vol. 4

https://i.imgur.com/5MWpler.jpg

I don't know if this is due to the way the comics are hosted by Image, or if this is already implemented but broken for Humble.

**Comment by mike-ferenduros** [comment]
I can see why this would be useful for Humble specifically, but at this point I don't want to add any more auto-grouping logic; I had to implement it for Image only because they don't give me any other way to group comics.
Sorry!

PS: I know didn't make this clear anywhere, but please post suggestions & bug-reports to Slack and I'll triage them there, cheers :)
